behaviors:
  MoveAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 0.0003
      beta: 0.03
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      # memory:
      #   sequence_length: 64
      #   memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
          strength: 0.1
          gamma: 0.99
          learning_rate: 1e-5
          network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 2
            vis_encode_type: simple
    keep_checkpoints: 5
    max_steps: 200000
    time_horizon: 64
    summary_freq: 2500

## NOTE: lesson completion criteria not required for terminal lesson
# target_x_easy 4.356
# target_x_hard 7.5

# target_z_easy -0.243
# target_z_hard -4.5
    
environment_parameters: ## DOCS: https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Training-ML-Agents.md#environment-parameters
  target_x: ## x coordinate of target 
    curriculum: ## list of lessons (note the "-")
      - name: MyFirstLesson # value holds x-coordinate of "easy" target
        completion_criteria: &first_lesson_criteria
          measure: progress
          behavior: MoveAgent
          signal_smoothing: true
          min_lesson_length: 1
          threshold: 0.1 ## 20 000 steps
          require_reset: true
        value: 4.356
      - name: MySecondLesson # value holds x-coordinate of "difficult" target (lesson two)
        value: 7.5
    
  target_z: ## z coordinate of target
    curriculum: ## list of lessons (note the "-")
      - name: MyFirstLesson # value holds x-coordinate of "easy" target
        completion_criteria: *first_lesson_criteria
        value: -0.243
      - name: MySecondLesson
        value: -4.5